;;; org-tempus-test.el --- Tests for org-tempus  -*- lexical-binding: t; -*-

(require 'cl-lib)
(require 'ert)
(require 'org-tempus)

(defmacro org-tempus-test--with-clocked-suspend-state (&rest body)
  "Run BODY with an active clock and suspend-detection defaults."
  (declare (indent 0) (debug t))
  `(let ((org-tempus-idle-check-interval 60)
         (org-tempus-auto-clock-enabled t)
         (org-tempus-auto-clock-out-seconds 240)
         (org-tempus-auto-clock-out-backdate t)
         (org-tempus--last-idle-check-time (seconds-to-time 1000))
         (org-tempus--clock-active-at-last-idle-check t)
         (org-tempus--auto-clock-out-time nil)
         (org-tempus--session-start-time (seconds-to-time 1000))
         (org-tempus--notification-state nil)
         (org-tempus-notifications-enabled nil))
     ,@body))

(ert-deftest org-tempus-start-timers-seeds-suspend-baseline-before-first-poll ()
  (let ((now (seconds-to-time 1000))
        (org-tempus-idle-check-interval 60)
        (org-tempus-notification-reset-seconds 0)
        (org-tempus--timer nil)
        (org-tempus--idle-timer nil)
        (org-tempus--notification-reset-timer nil)
        (org-tempus--last-idle-check-time nil)
        (org-tempus--clock-active-at-last-idle-check nil))
    (cl-letf (((symbol-function 'current-time) (lambda () now))
              ((symbol-function 'org-clock-is-active) (lambda () t))
              ((symbol-function 'run-at-time) (lambda (&rest _args) 'timer))
              ((symbol-function 'timerp) (lambda (_timer) nil)))
      (org-tempus--start-timers)
      (should (equal org-tempus--last-idle-check-time now))
      (should org-tempus--clock-active-at-last-idle-check))))

(ert-deftest org-tempus-regular-poll-is-not-a-suspend-gap ()
  (org-tempus-test--with-clocked-suspend-state
    (let ((org-tempus-auto-clock-out-seconds 30))
      (cl-letf (((symbol-function 'org-clock-is-active) (lambda () t)))
        (should-not
         (org-tempus--suspend-gap-seconds (seconds-to-time 1060)))))))

(ert-deftest org-tempus-detects-suspend-from-seeded-baseline ()
  (org-tempus-test--with-clocked-suspend-state
    (cl-letf (((symbol-function 'org-clock-is-active) (lambda () t)))
      (should (= (org-tempus--suspend-gap-seconds (seconds-to-time 87400))
                 86400))))) ;; a day

(ert-deftest org-tempus-detects-suspend-when-stale-baseline-saw-no-clock ()
  "A stale baseline must not leave a currently running clock open.
The current clock state is authoritative when deciding whether to repair a
long gap, even if the stale baseline recorded no active clock."
  (org-tempus-test--with-clocked-suspend-state
    (let ((org-tempus--clock-active-at-last-idle-check nil))
      (cl-letf (((symbol-function 'org-clock-is-active) (lambda () t)))
        (should (= (org-tempus--suspend-gap-seconds (seconds-to-time 87400))
                   86400)))))) ;; a day

(ert-deftest org-tempus-clock-in-refreshes-a-stale-baseline ()
  (let ((now (seconds-to-time 87400))
        (org-tempus-idle-check-interval 60)
        (org-tempus-auto-clock-enabled t)
        (org-tempus-auto-clock-out-seconds 240)
        (org-tempus--last-idle-check-time (seconds-to-time 1000))
        (org-tempus--clock-active-at-last-idle-check nil)
        (org-tempus--session-start-time nil)
        (org-tempus--notification-state nil)
        (org-clock-start-time (seconds-to-time 87400))
        (org-clock-out-time nil))
    (cl-letf (((symbol-function 'current-time) (lambda () now))
              ((symbol-function 'org-clock-is-active) (lambda () t)))
      (org-tempus--update-session-start)
      (should (equal org-tempus--last-idle-check-time now))
      (should org-tempus--clock-active-at-last-idle-check)
      (should-not (org-tempus--suspend-gap-seconds now)))))

(ert-deftest org-tempus-mode-line-repairs-suspend-before-reading-totals ()
  (org-tempus-test--with-clocked-suspend-state
    (let ((now (seconds-to-time 87400))
          (clock-active t)
          (clock-out-at nil)
          (total-read-after-clock-out nil)
          (org-tempus-mode-line-string ""))
      (cl-letf (((symbol-function 'current-time) (lambda () now))
                ((symbol-function 'org-clock-is-active) (lambda () clock-active))
                ((symbol-function 'org-clock-out)
                 (lambda (_switch _quiet at-time)
                   (setq clock-out-at at-time)
                   (setq clock-active nil)))
                ((symbol-function 'org-tempus--notify) #'ignore)
                ((symbol-function 'org-tempus--sum-today-minutes)
                 (lambda ()
                   (setq total-read-after-clock-out (not clock-active))
                   0))
                ((symbol-function 'org-tempus--current-break-duration)
                 (lambda () nil))
                ((symbol-function 'org-tempus--maybe-notify-total-threshold)
                 #'ignore)
                ((symbol-function 'org-tempus--maybe-update-dconf) #'ignore)
                ((symbol-function 'force-mode-line-update) #'ignore))
        (org-tempus--update-mode-line)
        (should (equal clock-out-at (seconds-to-time 1000)))
        (should total-read-after-clock-out)))))

(ert-deftest org-tempus-manual-clock-out-repairs-pending-suspend-gap ()
  (org-tempus-test--with-clocked-suspend-state
    (let ((now (seconds-to-time 87400))
          (clock-active t)
          (clock-out-at nil))
      (cl-letf (((symbol-function 'current-time) (lambda () now))
                ((symbol-function 'org-clock-is-active) (lambda () clock-active)))
        (org-tempus--clock-out-advice
         (lambda (_switch _quiet at-time)
           (setq clock-out-at at-time)
           (setq clock-active nil))
         nil nil nil)
        (should (equal clock-out-at (seconds-to-time 1000)))
        (should (equal org-tempus--last-idle-check-time now))
        (should-not org-tempus--clock-active-at-last-idle-check)))))

(ert-deftest org-tempus-manual-clock-out-preserves-explicit-time ()
  (org-tempus-test--with-clocked-suspend-state
    (let ((now (seconds-to-time 87400))
          (requested (seconds-to-time 2000))
          (clock-active t)
          (clock-out-at nil))
      (cl-letf (((symbol-function 'current-time) (lambda () now))
                ((symbol-function 'org-clock-is-active) (lambda () clock-active)))
        (org-tempus--clock-out-advice
         (lambda (_switch _quiet at-time)
           (setq clock-out-at at-time)
           (setq clock-active nil))
         nil nil requested)
        (should (equal clock-out-at requested))))))

(ert-deftest org-tempus-idle-active-streak-does-not-grow-while-clocked-in ()
  (let ((now (seconds-to-time 1060))
        (org-tempus-idle-check-interval 60)
        (org-tempus-idle-active-streak-seconds 120)
        (org-tempus-auto-clock-enabled t)
        (org-tempus-auto-clock-out-seconds 240)
        (org-tempus--last-idle-check-time (seconds-to-time 1000))
        (org-tempus--clock-active-at-last-idle-check t)
        (org-tempus--idle-active-streak 540))
    (cl-letf (((symbol-function 'current-time) (lambda () now))
              ((symbol-function 'org-clock-is-active) (lambda () t))
              ((symbol-function 'org-tempus--session-idle-seconds)
               (lambda () 0.5)))
      (org-tempus--handle-idle)
      (should (= org-tempus--idle-active-streak 0)))))

(provide 'org-tempus-test)
;;; org-tempus-test.el ends here
